/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PreiseRouteImport } from './routes/preise'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as FunktionenRouteImport } from './routes/funktionen'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppZeitenRouteImport } from './routes/_authenticated/app.zeiten'
import { Route as AuthenticatedAppTeamRouteImport } from './routes/_authenticated/app.team'
import { Route as AuthenticatedAppProfilRouteImport } from './routes/_authenticated/app.profil'
import { Route as AuthenticatedAppPlanRouteImport } from './routes/_authenticated/app.plan'
import { Route as AuthenticatedAppEinstellungenRouteImport } from './routes/_authenticated/app.einstellungen'
import { Route as AuthenticatedAppBaustellenRouteImport } from './routes/_authenticated/app.baustellen'

const PreiseRoute = PreiseRouteImport.update({
  id: '/preise',
  path: '/preise',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const FunktionenRoute = FunktionenRouteImport.update({
  id: '/funktionen',
  path: '/funktionen',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppZeitenRoute = AuthenticatedAppZeitenRouteImport.update({
  id: '/zeiten',
  path: '/zeiten',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTeamRoute = AuthenticatedAppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppProfilRoute = AuthenticatedAppProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPlanRoute = AuthenticatedAppPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppEinstellungenRoute =
  AuthenticatedAppEinstellungenRouteImport.update({
    id: '/einstellungen',
    path: '/einstellungen',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBaustellenRoute =
  AuthenticatedAppBaustellenRouteImport.update({
    id: '/baustellen',
    path: '/baustellen',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/funktionen': typeof FunktionenRoute
  '/kontakt': typeof KontaktRoute
  '/preise': typeof PreiseRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/baustellen': typeof AuthenticatedAppBaustellenRoute
  '/app/einstellungen': typeof AuthenticatedAppEinstellungenRoute
  '/app/plan': typeof AuthenticatedAppPlanRoute
  '/app/profil': typeof AuthenticatedAppProfilRoute
  '/app/team': typeof AuthenticatedAppTeamRoute
  '/app/zeiten': typeof AuthenticatedAppZeitenRoute
  '/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/funktionen': typeof FunktionenRoute
  '/kontakt': typeof KontaktRoute
  '/preise': typeof PreiseRoute
  '/app/baustellen': typeof AuthenticatedAppBaustellenRoute
  '/app/einstellungen': typeof AuthenticatedAppEinstellungenRoute
  '/app/plan': typeof AuthenticatedAppPlanRoute
  '/app/profil': typeof AuthenticatedAppProfilRoute
  '/app/team': typeof AuthenticatedAppTeamRoute
  '/app/zeiten': typeof AuthenticatedAppZeitenRoute
  '/app': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/funktionen': typeof FunktionenRoute
  '/kontakt': typeof KontaktRoute
  '/preise': typeof PreiseRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/baustellen': typeof AuthenticatedAppBaustellenRoute
  '/_authenticated/app/einstellungen': typeof AuthenticatedAppEinstellungenRoute
  '/_authenticated/app/plan': typeof AuthenticatedAppPlanRoute
  '/_authenticated/app/profil': typeof AuthenticatedAppProfilRoute
  '/_authenticated/app/team': typeof AuthenticatedAppTeamRoute
  '/_authenticated/app/zeiten': typeof AuthenticatedAppZeitenRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/funktionen'
    | '/kontakt'
    | '/preise'
    | '/app'
    | '/app/baustellen'
    | '/app/einstellungen'
    | '/app/plan'
    | '/app/profil'
    | '/app/team'
    | '/app/zeiten'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/funktionen'
    | '/kontakt'
    | '/preise'
    | '/app/baustellen'
    | '/app/einstellungen'
    | '/app/plan'
    | '/app/profil'
    | '/app/team'
    | '/app/zeiten'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/funktionen'
    | '/kontakt'
    | '/preise'
    | '/_authenticated/app'
    | '/_authenticated/app/baustellen'
    | '/_authenticated/app/einstellungen'
    | '/_authenticated/app/plan'
    | '/_authenticated/app/profil'
    | '/_authenticated/app/team'
    | '/_authenticated/app/zeiten'
    | '/_authenticated/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  FunktionenRoute: typeof FunktionenRoute
  KontaktRoute: typeof KontaktRoute
  PreiseRoute: typeof PreiseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/preise': {
      id: '/preise'
      path: '/preise'
      fullPath: '/preise'
      preLoaderRoute: typeof PreiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funktionen': {
      id: '/funktionen'
      path: '/funktionen'
      fullPath: '/funktionen'
      preLoaderRoute: typeof FunktionenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/zeiten': {
      id: '/_authenticated/app/zeiten'
      path: '/zeiten'
      fullPath: '/app/zeiten'
      preLoaderRoute: typeof AuthenticatedAppZeitenRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/team': {
      id: '/_authenticated/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AuthenticatedAppTeamRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/profil': {
      id: '/_authenticated/app/profil'
      path: '/profil'
      fullPath: '/app/profil'
      preLoaderRoute: typeof AuthenticatedAppProfilRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/plan': {
      id: '/_authenticated/app/plan'
      path: '/plan'
      fullPath: '/app/plan'
      preLoaderRoute: typeof AuthenticatedAppPlanRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/einstellungen': {
      id: '/_authenticated/app/einstellungen'
      path: '/einstellungen'
      fullPath: '/app/einstellungen'
      preLoaderRoute: typeof AuthenticatedAppEinstellungenRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/baustellen': {
      id: '/_authenticated/app/baustellen'
      path: '/baustellen'
      fullPath: '/app/baustellen'
      preLoaderRoute: typeof AuthenticatedAppBaustellenRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppBaustellenRoute: typeof AuthenticatedAppBaustellenRoute
  AuthenticatedAppEinstellungenRoute: typeof AuthenticatedAppEinstellungenRoute
  AuthenticatedAppPlanRoute: typeof AuthenticatedAppPlanRoute
  AuthenticatedAppProfilRoute: typeof AuthenticatedAppProfilRoute
  AuthenticatedAppTeamRoute: typeof AuthenticatedAppTeamRoute
  AuthenticatedAppZeitenRoute: typeof AuthenticatedAppZeitenRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppBaustellenRoute: AuthenticatedAppBaustellenRoute,
  AuthenticatedAppEinstellungenRoute: AuthenticatedAppEinstellungenRoute,
  AuthenticatedAppPlanRoute: AuthenticatedAppPlanRoute,
  AuthenticatedAppProfilRoute: AuthenticatedAppProfilRoute,
  AuthenticatedAppTeamRoute: AuthenticatedAppTeamRoute,
  AuthenticatedAppZeitenRoute: AuthenticatedAppZeitenRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FunktionenRoute: FunktionenRoute,
  KontaktRoute: KontaktRoute,
  PreiseRoute: PreiseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
