/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as FunktionenRouteImport } from './routes/funktionen'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as PreiseRouteImport } from './routes/preise'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppAbwesenheitenRouteImport } from './routes/_authenticated/app.abwesenheiten'
import { Route as AuthenticatedAppBueroRouteImport } from './routes/_authenticated/app.buero'
import { Route as AuthenticatedAppEinstellungenRouteImport } from './routes/_authenticated/app.einstellungen'
import { Route as AuthenticatedAppGeraeteRouteImport } from './routes/_authenticated/app.geraete'
import { Route as AuthenticatedAppKiAssistentRouteImport } from './routes/_authenticated/app.ki-assistent'
import { Route as AuthenticatedAppMitarbeiterRouteImport } from './routes/_authenticated/app.mitarbeiter'
import { Route as AuthenticatedAppPlanRouteImport } from './routes/_authenticated/app.plan'
import { Route as AuthenticatedAppZeitenRouteImport } from './routes/_authenticated/app.zeiten'
import { Route as AuthenticatedAppBaustellenIndexRouteImport } from './routes/_authenticated/app.baustellen.index'
import { Route as AuthenticatedAppBaustellenIdRouteImport } from './routes/_authenticated/app.baustellen.$id'
import { Route as AuthenticatedAppKundenCustomerIdRouteImport } from './routes/_authenticated/app.kunden.$customerId'
import { Route as AuthenticatedAppProfilIndexRouteImport } from './routes/_authenticated/app.profil.index'
import { Route as AuthenticatedAppProfilDatenRouteImport } from './routes/_authenticated/app.profil.daten'
import { Route as AuthenticatedAppProfilDokumenteRouteImport } from './routes/_authenticated/app.profil.dokumente'
import { Route as AuthenticatedAppBaustellenIdIndexRouteImport } from './routes/_authenticated/app.baustellen.$id.index'
import { Route as AuthenticatedAppBaustellenIdAufgabenRouteImport } from './routes/_authenticated/app.baustellen.$id.aufgaben'
import { Route as AuthenticatedAppBaustellenIdInfoRouteImport } from './routes/_authenticated/app.baustellen.$id.info'
import { Route as AuthenticatedAppBaustellenIdMedienRouteImport } from './routes/_authenticated/app.baustellen.$id.medien'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const FunktionenRoute = FunktionenRouteImport.update({
  id: '/funktionen',
  path: '/funktionen',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const PreiseRoute = PreiseRouteImport.update({
  id: '/preise',
  path: '/preise',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAbwesenheitenRoute =
  AuthenticatedAppAbwesenheitenRouteImport.update({
    id: '/abwesenheiten',
    path: '/abwesenheiten',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBueroRoute = AuthenticatedAppBueroRouteImport.update({
  id: '/buero',
  path: '/buero',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppEinstellungenRoute =
  AuthenticatedAppEinstellungenRouteImport.update({
    id: '/einstellungen',
    path: '/einstellungen',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppGeraeteRoute = AuthenticatedAppGeraeteRouteImport.update({
  id: '/geraete',
  path: '/geraete',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppKiAssistentRoute =
  AuthenticatedAppKiAssistentRouteImport.update({
    id: '/ki-assistent',
    path: '/ki-assistent',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMitarbeiterRoute =
  AuthenticatedAppMitarbeiterRouteImport.update({
    id: '/mitarbeiter',
    path: '/mitarbeiter',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPlanRoute = AuthenticatedAppPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppZeitenRoute = AuthenticatedAppZeitenRouteImport.update({
  id: '/zeiten',
  path: '/zeiten',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppBaustellenIndexRoute =
  AuthenticatedAppBaustellenIndexRouteImport.update({
    id: '/baustellen/',
    path: '/baustellen/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBaustellenIdRoute =
  AuthenticatedAppBaustellenIdRouteImport.update({
    id: '/baustellen/$id',
    path: '/baustellen/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppKundenCustomerIdRoute =
  AuthenticatedAppKundenCustomerIdRouteImport.update({
    id: '/kunden/$customerId',
    path: '/kunden/$customerId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProfilIndexRoute =
  AuthenticatedAppProfilIndexRouteImport.update({
    id: '/profil/',
    path: '/profil/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProfilDatenRoute =
  AuthenticatedAppProfilDatenRouteImport.update({
    id: '/profil/daten',
    path: '/profil/daten',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProfilDokumenteRoute =
  AuthenticatedAppProfilDokumenteRouteImport.update({
    id: '/profil/dokumente',
    path: '/profil/dokumente',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBaustellenIdIndexRoute =
  AuthenticatedAppBaustellenIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppBaustellenIdRoute,
  } as any)
const AuthenticatedAppBaustellenIdAufgabenRoute =
  AuthenticatedAppBaustellenIdAufgabenRouteImport.update({
    id: '/aufgaben',
    path: '/aufgaben',
    getParentRoute: () => AuthenticatedAppBaustellenIdRoute,
  } as any)
const AuthenticatedAppBaustellenIdInfoRoute =
  AuthenticatedAppBaustellenIdInfoRouteImport.update({
    id: '/info',
    path: '/info',
    getParentRoute: () => AuthenticatedAppBaustellenIdRoute,
  } as any)
const AuthenticatedAppBaustellenIdMedienRoute =
  AuthenticatedAppBaustellenIdMedienRouteImport.update({
    id: '/medien',
    path: '/medien',
    getParentRoute: () => AuthenticatedAppBaustellenIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/auth': typeof AuthRoute
  '/datenschutz': typeof DatenschutzRoute
  '/funktionen': typeof FunktionenRoute
  '/healthz': typeof HealthzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/preise': typeof PreiseRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/abwesenheiten': typeof AuthenticatedAppAbwesenheitenRoute
  '/app/buero': typeof AuthenticatedAppBueroRoute
  '/app/einstellungen': typeof AuthenticatedAppEinstellungenRoute
  '/app/geraete': typeof AuthenticatedAppGeraeteRoute
  '/app/ki-assistent': typeof AuthenticatedAppKiAssistentRoute
  '/app/mitarbeiter': typeof AuthenticatedAppMitarbeiterRoute
  '/app/plan': typeof AuthenticatedAppPlanRoute
  '/app/zeiten': typeof AuthenticatedAppZeitenRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/baustellen/$id': typeof AuthenticatedAppBaustellenIdRouteWithChildren
  '/app/kunden/$customerId': typeof AuthenticatedAppKundenCustomerIdRoute
  '/app/profil/daten': typeof AuthenticatedAppProfilDatenRoute
  '/app/profil/dokumente': typeof AuthenticatedAppProfilDokumenteRoute
  '/app/baustellen/': typeof AuthenticatedAppBaustellenIndexRoute
  '/app/profil/': typeof AuthenticatedAppProfilIndexRoute
  '/app/baustellen/$id/aufgaben': typeof AuthenticatedAppBaustellenIdAufgabenRoute
  '/app/baustellen/$id/info': typeof AuthenticatedAppBaustellenIdInfoRoute
  '/app/baustellen/$id/medien': typeof AuthenticatedAppBaustellenIdMedienRoute
  '/app/baustellen/$id/': typeof AuthenticatedAppBaustellenIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/auth': typeof AuthRoute
  '/datenschutz': typeof DatenschutzRoute
  '/funktionen': typeof FunktionenRoute
  '/healthz': typeof HealthzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/preise': typeof PreiseRoute
  '/app/abwesenheiten': typeof AuthenticatedAppAbwesenheitenRoute
  '/app/buero': typeof AuthenticatedAppBueroRoute
  '/app/einstellungen': typeof AuthenticatedAppEinstellungenRoute
  '/app/geraete': typeof AuthenticatedAppGeraeteRoute
  '/app/ki-assistent': typeof AuthenticatedAppKiAssistentRoute
  '/app/mitarbeiter': typeof AuthenticatedAppMitarbeiterRoute
  '/app/plan': typeof AuthenticatedAppPlanRoute
  '/app/zeiten': typeof AuthenticatedAppZeitenRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/kunden/$customerId': typeof AuthenticatedAppKundenCustomerIdRoute
  '/app/profil/daten': typeof AuthenticatedAppProfilDatenRoute
  '/app/profil/dokumente': typeof AuthenticatedAppProfilDokumenteRoute
  '/app/baustellen': typeof AuthenticatedAppBaustellenIndexRoute
  '/app/profil': typeof AuthenticatedAppProfilIndexRoute
  '/app/baustellen/$id/aufgaben': typeof AuthenticatedAppBaustellenIdAufgabenRoute
  '/app/baustellen/$id/info': typeof AuthenticatedAppBaustellenIdInfoRoute
  '/app/baustellen/$id/medien': typeof AuthenticatedAppBaustellenIdMedienRoute
  '/app/baustellen/$id': typeof AuthenticatedAppBaustellenIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/auth': typeof AuthRoute
  '/datenschutz': typeof DatenschutzRoute
  '/funktionen': typeof FunktionenRoute
  '/healthz': typeof HealthzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/preise': typeof PreiseRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/abwesenheiten': typeof AuthenticatedAppAbwesenheitenRoute
  '/_authenticated/app/buero': typeof AuthenticatedAppBueroRoute
  '/_authenticated/app/einstellungen': typeof AuthenticatedAppEinstellungenRoute
  '/_authenticated/app/geraete': typeof AuthenticatedAppGeraeteRoute
  '/_authenticated/app/ki-assistent': typeof AuthenticatedAppKiAssistentRoute
  '/_authenticated/app/mitarbeiter': typeof AuthenticatedAppMitarbeiterRoute
  '/_authenticated/app/plan': typeof AuthenticatedAppPlanRoute
  '/_authenticated/app/zeiten': typeof AuthenticatedAppZeitenRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/baustellen/$id': typeof AuthenticatedAppBaustellenIdRouteWithChildren
  '/_authenticated/app/kunden/$customerId': typeof AuthenticatedAppKundenCustomerIdRoute
  '/_authenticated/app/profil/daten': typeof AuthenticatedAppProfilDatenRoute
  '/_authenticated/app/profil/dokumente': typeof AuthenticatedAppProfilDokumenteRoute
  '/_authenticated/app/baustellen/': typeof AuthenticatedAppBaustellenIndexRoute
  '/_authenticated/app/profil/': typeof AuthenticatedAppProfilIndexRoute
  '/_authenticated/app/baustellen/$id/aufgaben': typeof AuthenticatedAppBaustellenIdAufgabenRoute
  '/_authenticated/app/baustellen/$id/info': typeof AuthenticatedAppBaustellenIdInfoRoute
  '/_authenticated/app/baustellen/$id/medien': typeof AuthenticatedAppBaustellenIdMedienRoute
  '/_authenticated/app/baustellen/$id/': typeof AuthenticatedAppBaustellenIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/auth'
    | '/datenschutz'
    | '/funktionen'
    | '/healthz'
    | '/impressum'
    | '/kontakt'
    | '/preise'
    | '/app'
    | '/app/abwesenheiten'
    | '/app/buero'
    | '/app/einstellungen'
    | '/app/geraete'
    | '/app/ki-assistent'
    | '/app/mitarbeiter'
    | '/app/plan'
    | '/app/zeiten'
    | '/app/'
    | '/app/baustellen/$id'
    | '/app/kunden/$customerId'
    | '/app/profil/daten'
    | '/app/profil/dokumente'
    | '/app/baustellen/'
    | '/app/profil/'
    | '/app/baustellen/$id/aufgaben'
    | '/app/baustellen/$id/info'
    | '/app/baustellen/$id/medien'
    | '/app/baustellen/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/auth'
    | '/datenschutz'
    | '/funktionen'
    | '/healthz'
    | '/impressum'
    | '/kontakt'
    | '/preise'
    | '/app/abwesenheiten'
    | '/app/buero'
    | '/app/einstellungen'
    | '/app/geraete'
    | '/app/ki-assistent'
    | '/app/mitarbeiter'
    | '/app/plan'
    | '/app/zeiten'
    | '/app'
    | '/app/kunden/$customerId'
    | '/app/profil/daten'
    | '/app/profil/dokumente'
    | '/app/baustellen'
    | '/app/profil'
    | '/app/baustellen/$id/aufgaben'
    | '/app/baustellen/$id/info'
    | '/app/baustellen/$id/medien'
    | '/app/baustellen/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/accept-invite'
    | '/auth'
    | '/datenschutz'
    | '/funktionen'
    | '/healthz'
    | '/impressum'
    | '/kontakt'
    | '/preise'
    | '/_authenticated/app'
    | '/_authenticated/app/abwesenheiten'
    | '/_authenticated/app/buero'
    | '/_authenticated/app/einstellungen'
    | '/_authenticated/app/geraete'
    | '/_authenticated/app/ki-assistent'
    | '/_authenticated/app/mitarbeiter'
    | '/_authenticated/app/plan'
    | '/_authenticated/app/zeiten'
    | '/_authenticated/app/'
    | '/_authenticated/app/baustellen/$id'
    | '/_authenticated/app/kunden/$customerId'
    | '/_authenticated/app/profil/daten'
    | '/_authenticated/app/profil/dokumente'
    | '/_authenticated/app/baustellen/'
    | '/_authenticated/app/profil/'
    | '/_authenticated/app/baustellen/$id/aufgaben'
    | '/_authenticated/app/baustellen/$id/info'
    | '/_authenticated/app/baustellen/$id/medien'
    | '/_authenticated/app/baustellen/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  AuthRoute: typeof AuthRoute
  DatenschutzRoute: typeof DatenschutzRoute
  FunktionenRoute: typeof FunktionenRoute
  HealthzRoute: typeof HealthzRoute
  ImpressumRoute: typeof ImpressumRoute
  KontaktRoute: typeof KontaktRoute
  PreiseRoute: typeof PreiseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funktionen': {
      id: '/funktionen'
      path: '/funktionen'
      fullPath: '/funktionen'
      preLoaderRoute: typeof FunktionenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preise': {
      id: '/preise'
      path: '/preise'
      fullPath: '/preise'
      preLoaderRoute: typeof PreiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/abwesenheiten': {
      id: '/_authenticated/app/abwesenheiten'
      path: '/abwesenheiten'
      fullPath: '/app/abwesenheiten'
      preLoaderRoute: typeof AuthenticatedAppAbwesenheitenRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/buero': {
      id: '/_authenticated/app/buero'
      path: '/buero'
      fullPath: '/app/buero'
      preLoaderRoute: typeof AuthenticatedAppBueroRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/einstellungen': {
      id: '/_authenticated/app/einstellungen'
      path: '/einstellungen'
      fullPath: '/app/einstellungen'
      preLoaderRoute: typeof AuthenticatedAppEinstellungenRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/geraete': {
      id: '/_authenticated/app/geraete'
      path: '/geraete'
      fullPath: '/app/geraete'
      preLoaderRoute: typeof AuthenticatedAppGeraeteRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ki-assistent': {
      id: '/_authenticated/app/ki-assistent'
      path: '/ki-assistent'
      fullPath: '/app/ki-assistent'
      preLoaderRoute: typeof AuthenticatedAppKiAssistentRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/mitarbeiter': {
      id: '/_authenticated/app/mitarbeiter'
      path: '/mitarbeiter'
      fullPath: '/app/mitarbeiter'
      preLoaderRoute: typeof AuthenticatedAppMitarbeiterRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/plan': {
      id: '/_authenticated/app/plan'
      path: '/plan'
      fullPath: '/app/plan'
      preLoaderRoute: typeof AuthenticatedAppPlanRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/zeiten': {
      id: '/_authenticated/app/zeiten'
      path: '/zeiten'
      fullPath: '/app/zeiten'
      preLoaderRoute: typeof AuthenticatedAppZeitenRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/baustellen/': {
      id: '/_authenticated/app/baustellen/'
      path: '/baustellen'
      fullPath: '/app/baustellen/'
      preLoaderRoute: typeof AuthenticatedAppBaustellenIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/baustellen/$id': {
      id: '/_authenticated/app/baustellen/$id'
      path: '/baustellen/$id'
      fullPath: '/app/baustellen/$id'
      preLoaderRoute: typeof AuthenticatedAppBaustellenIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/kunden/$customerId': {
      id: '/_authenticated/app/kunden/$customerId'
      path: '/kunden/$customerId'
      fullPath: '/app/kunden/$customerId'
      preLoaderRoute: typeof AuthenticatedAppKundenCustomerIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/profil/': {
      id: '/_authenticated/app/profil/'
      path: '/profil'
      fullPath: '/app/profil/'
      preLoaderRoute: typeof AuthenticatedAppProfilIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/profil/daten': {
      id: '/_authenticated/app/profil/daten'
      path: '/profil/daten'
      fullPath: '/app/profil/daten'
      preLoaderRoute: typeof AuthenticatedAppProfilDatenRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/profil/dokumente': {
      id: '/_authenticated/app/profil/dokumente'
      path: '/profil/dokumente'
      fullPath: '/app/profil/dokumente'
      preLoaderRoute: typeof AuthenticatedAppProfilDokumenteRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/baustellen/$id/': {
      id: '/_authenticated/app/baustellen/$id/'
      path: '/'
      fullPath: '/app/baustellen/$id/'
      preLoaderRoute: typeof AuthenticatedAppBaustellenIdIndexRouteImport
      parentRoute: typeof AuthenticatedAppBaustellenIdRoute
    }
    '/_authenticated/app/baustellen/$id/aufgaben': {
      id: '/_authenticated/app/baustellen/$id/aufgaben'
      path: '/aufgaben'
      fullPath: '/app/baustellen/$id/aufgaben'
      preLoaderRoute: typeof AuthenticatedAppBaustellenIdAufgabenRouteImport
      parentRoute: typeof AuthenticatedAppBaustellenIdRoute
    }
    '/_authenticated/app/baustellen/$id/info': {
      id: '/_authenticated/app/baustellen/$id/info'
      path: '/info'
      fullPath: '/app/baustellen/$id/info'
      preLoaderRoute: typeof AuthenticatedAppBaustellenIdInfoRouteImport
      parentRoute: typeof AuthenticatedAppBaustellenIdRoute
    }
    '/_authenticated/app/baustellen/$id/medien': {
      id: '/_authenticated/app/baustellen/$id/medien'
      path: '/medien'
      fullPath: '/app/baustellen/$id/medien'
      preLoaderRoute: typeof AuthenticatedAppBaustellenIdMedienRouteImport
      parentRoute: typeof AuthenticatedAppBaustellenIdRoute
    }
  }
}

interface AuthenticatedAppBaustellenIdRouteChildren {
  AuthenticatedAppBaustellenIdAufgabenRoute: typeof AuthenticatedAppBaustellenIdAufgabenRoute
  AuthenticatedAppBaustellenIdInfoRoute: typeof AuthenticatedAppBaustellenIdInfoRoute
  AuthenticatedAppBaustellenIdMedienRoute: typeof AuthenticatedAppBaustellenIdMedienRoute
  AuthenticatedAppBaustellenIdIndexRoute: typeof AuthenticatedAppBaustellenIdIndexRoute
}

const AuthenticatedAppBaustellenIdRouteChildren: AuthenticatedAppBaustellenIdRouteChildren =
  {
    AuthenticatedAppBaustellenIdAufgabenRoute:
      AuthenticatedAppBaustellenIdAufgabenRoute,
    AuthenticatedAppBaustellenIdInfoRoute:
      AuthenticatedAppBaustellenIdInfoRoute,
    AuthenticatedAppBaustellenIdMedienRoute:
      AuthenticatedAppBaustellenIdMedienRoute,
    AuthenticatedAppBaustellenIdIndexRoute:
      AuthenticatedAppBaustellenIdIndexRoute,
  }

const AuthenticatedAppBaustellenIdRouteWithChildren =
  AuthenticatedAppBaustellenIdRoute._addFileChildren(
    AuthenticatedAppBaustellenIdRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAbwesenheitenRoute: typeof AuthenticatedAppAbwesenheitenRoute
  AuthenticatedAppBueroRoute: typeof AuthenticatedAppBueroRoute
  AuthenticatedAppEinstellungenRoute: typeof AuthenticatedAppEinstellungenRoute
  AuthenticatedAppGeraeteRoute: typeof AuthenticatedAppGeraeteRoute
  AuthenticatedAppKiAssistentRoute: typeof AuthenticatedAppKiAssistentRoute
  AuthenticatedAppMitarbeiterRoute: typeof AuthenticatedAppMitarbeiterRoute
  AuthenticatedAppPlanRoute: typeof AuthenticatedAppPlanRoute
  AuthenticatedAppZeitenRoute: typeof AuthenticatedAppZeitenRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppBaustellenIdRoute: typeof AuthenticatedAppBaustellenIdRouteWithChildren
  AuthenticatedAppKundenCustomerIdRoute: typeof AuthenticatedAppKundenCustomerIdRoute
  AuthenticatedAppProfilDatenRoute: typeof AuthenticatedAppProfilDatenRoute
  AuthenticatedAppProfilDokumenteRoute: typeof AuthenticatedAppProfilDokumenteRoute
  AuthenticatedAppBaustellenIndexRoute: typeof AuthenticatedAppBaustellenIndexRoute
  AuthenticatedAppProfilIndexRoute: typeof AuthenticatedAppProfilIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAbwesenheitenRoute: AuthenticatedAppAbwesenheitenRoute,
  AuthenticatedAppBueroRoute: AuthenticatedAppBueroRoute,
  AuthenticatedAppEinstellungenRoute: AuthenticatedAppEinstellungenRoute,
  AuthenticatedAppGeraeteRoute: AuthenticatedAppGeraeteRoute,
  AuthenticatedAppKiAssistentRoute: AuthenticatedAppKiAssistentRoute,
  AuthenticatedAppMitarbeiterRoute: AuthenticatedAppMitarbeiterRoute,
  AuthenticatedAppPlanRoute: AuthenticatedAppPlanRoute,
  AuthenticatedAppZeitenRoute: AuthenticatedAppZeitenRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppBaustellenIdRoute:
    AuthenticatedAppBaustellenIdRouteWithChildren,
  AuthenticatedAppKundenCustomerIdRoute: AuthenticatedAppKundenCustomerIdRoute,
  AuthenticatedAppProfilDatenRoute: AuthenticatedAppProfilDatenRoute,
  AuthenticatedAppProfilDokumenteRoute: AuthenticatedAppProfilDokumenteRoute,
  AuthenticatedAppBaustellenIndexRoute: AuthenticatedAppBaustellenIndexRoute,
  AuthenticatedAppProfilIndexRoute: AuthenticatedAppProfilIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  AuthRoute: AuthRoute,
  DatenschutzRoute: DatenschutzRoute,
  FunktionenRoute: FunktionenRoute,
  HealthzRoute: HealthzRoute,
  ImpressumRoute: ImpressumRoute,
  KontaktRoute: KontaktRoute,
  PreiseRoute: PreiseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
